### ISSUE TITLE
Npm warning - renaming jade to pug

### ISSUE THREAD

**Issue by samio80** [monokrome/jaded-brunch#22]
By doing npm install you get the following warning:

Jade has been renamed to pug, please install the latest version of pug instead of jade

Can you please replace the dependency so instead of jade you include pug?

**Comment by monokrome** [comment]
Thanks, @samio80. I realized this one the other day. Trying to figure out if I should rename this repo as well 👍

**Comment by samio80** [comment]
very good point :)

**Comment by monokrome** [comment]
@samio80 Problem solved in version 2.3.0. Thanks!!!

**Comment by samio80** [comment]
Still happenning in version 2.3.0
jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade

**Comment by monokrome** [comment]
@samio80 Sorry, thought this was the other issue. I didn't fix this yet, but it won't break anything :)

**Comment by webdif** [comment]
Is this repo will be renamed `pug-brunch`, or rather `puged-brunch` in order to let the actual `jade-brunch`  repo rename into `pug-brunch`?
